### ISSUE TITLE
[勘误] 第三章3.5.2命令 4.集合见运算

### ISSUE THREAD

**Issue by majunjonken** [luin/redis-book-assets#1]
最近在看《Redis入门指南(第2版)》，发现有笔误的地方望修改：
第三章3.5.2命令 4.集合见运算 有写到 _A-B={x|x∈A且x∈B}_，应该是 _A-B={x|x∈A且x∉B}_，tks

**Comment by luin** [comment]
收到，多谢反馈！

**Comment by majunjonken** [comment]
;)
👍
